### ISSUE TITLE
Usage with Preact

### ISSUE THREAD

**Issue by itsmitul** [jaydenseric/next-graphql-react#6]
While using next-graphql-react on nextjs along with Preact, I am getting the following error:

`UnhandledPromiseRejectionWarning: Error: Cannot find module 'react-dom/server.node'
`

**Comment by jaydenseric** [comment]
Probably because you need to alias this require path to whatever the Preact alternative is:

https://github.com/jaydenseric/graphql-react/blob/b427ed3b2f03773216aaa95e611f5f027be13138/src/server/ssr.js#L3

Closing because this issue is not specific to this particular repo, and also because Preact support for `graphql-react` was not a goal. Please share if you are able to get it working though; if there is anything easy we can do to better support Preact let us know!
